apiVersion: v1
kind: Pod
metadata:
  name: dlpod
  labels:
    app: dlpod
spec:
  containers:
    - name: dlpod-app
      image: localhost/dlpod:latest
      ports:
        - containerPort: 5000
          hostPort: 8765        # change this to whatever port you want on the host
          protocol: TCP
      env:
        - name: DOWNLOAD_DIR
          value: /downloads
        - name: DATA_DIR
          value: /data
        - name: SPOTIPY_CLIENT_ID
          value: "YOUR_CLIENT_ID"
        - name: SPOTIPY_CLIENT_SECRET
          value: "YOUR_CLIENT_SECRET"
        - name: GENIUS_ACCESS_TOKEN
          value: "YOUR_GENIUS_TOKEN"
      volumeMounts:
        - mountPath: /downloads
          name: downloads-vol
        - mountPath: /data
          name: data-vol
      resources:
        limits:
          memory: 250Mi
        requests:
          memory: 64Mi
  volumes:
    - name: downloads-vol
      hostPath:
        # point this at your host path
        path: /srv/Downloads/media
        type: DirectoryOrCreate
    - name: data-vol
      hostPath:
        path: /opt/dlpod
        type: DirectoryOrCreate
  restartPolicy: Always
